updated shell config

diff --git a/config/.local/bin/dmenu/dmenuiwd b/config/.local/bin/dmenu/dmenuiwd
--- a/config/.local/bin/dmenu/dmenuiwd
+++ b/config/.local/bin/dmenu/dmenuiwd
@@ -8,8 +8,14 @@ add() {
 	list_known=$(iwctl known-networks list | awk 'NR>4 && $0 !~ /^$/ { print $1 }')
 	list=$(comm -23 <(sort -u <<<"$list_all") <(sort -u <<<"$list_known"))
 	ssid=$(printf "%s" "$list" | dmenu -i -p "add") || return
-	pass=$(dmenu -P -p "Enter password for $choice")
-	iwctl --passphrase "$pass" station $interface connect "$ssid"
+	pass=$(dmenu -P -p "Enter password for $choice") || return
+	if iwctl --passphrase "$pass" station $interface connect "$ssid"; then
+		notify-send "Successfully added $ssid"
+		exit
+	else
+		notify-send "Wrong password $ssid"
+		return
+	fi
 }
 
 switch() {
@@ -21,7 +27,13 @@ switch() {
 		return
 	}
 	ssid=$(printf "%s" "$list" | dmenu -i -p "switch") || return
-	iwctl station $interface connect "$ssid"
+	if iwctl station $interface connect "$ssid"; then
+		notify-send "Successfully connected with $ssid"
+		exit
+	else
+		notify-send "Failed to connect with $ssid"
+		return
+	fi
 }
 
 forget() {
@@ -31,33 +43,35 @@ forget() {
 		return
 	}
 	ssid=$(printf "%s" "$list" | dmenu -i -p "forget") || return
-	iwctl known-networks "$ssid" forget
+	iwctl known-networks "$ssid" forget && notify-send "Successfully forgot $ssid" && exit
 }
 
 scan() {
 	iwctl station $interface scan
+	notify-send "Network scanning..."
 }
 
 if ! pgrep -x iwd; then
 	if ! (sudo -A systemctl start iwd && sudo -A systemctl enable iwd); then
-		notify-send "❌ Error." "Unable to start iwd."
+		notify-send -u critical "❌ Error." "Unable to start iwd."
 		exit
 	fi
 fi
 
 if ! pgrep -x dhcpcd; then
 	if ! (sudo -A systemctl start dhcpcd && sudo -A systemctl enable dhcpcd);then
-		notify-send "❌ Error." "Unable to start dhcpcd."
+		notify-send -u critical "❌ Error." "Unable to start dhcpcd."
 		exit
 	fi
 fi
 
 while true; do
 	options="switch\nadd\nscan\nforget"
-	choice=$(printf "%b" "$options" | dmenu -i -p "network") || exit
+	choice=$(printf "%b" "$options" | dmenu -i -p "Network") || exit
 	case $choice in
 	"add") add ;;
 	"switch") switch ;;
 	"forget") forget ;;
+	"scan") scan ;;
 	esac
 done
